/* eslint-disable @typescript-eslint/ban-ts-comment */
import React, { Suspense } from "react"
import { Canvas } from "@react-three/fiber"
import { Loader, useGLTF, OrbitControls, PerspectiveCamera, Stars } from "@react-three/drei"
import { Stack, Text, Box } from "@chakra-ui/react"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: overlaps (https://sketchfab.com/overlaps)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/
function Model({ url }) {
  const { nodes } = useGLTF(url)
  return (
    <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -7, 0]} scale={7}>
      <group rotation={[Math.PI / 13.5, -Math.PI / 5.8, Math.PI / 5.6]}>
        <mesh receiveShadow castShadow geometry={nodes.planet002.geometry} material={nodes.planet002.material} />
        <mesh geometry={nodes.planet003.geometry} material={nodes.planet003.material} />
      </group>
    </group>
  )
}

export function Header() {
  return (
    <Box height={["60vh", "100vh"]} zIndex={10} position="relative">
      <Stack
        zIndex={10}
        position="absolute"
        top={[40, 0]}
        left={0}
        mx="auto"
        width="full"
        maxW={["xs", "3xl"]}
        px={4}
        pl={[4, 32]}
        pt={[20, 40]}
      >
        <Text fontSize={["3xl", "5xl", "7xl"]} lineHeight={["short", "normal"]} fontWeight="black" fontFamily="Inter" as="h1">
          <Box as="span" color="blue.400">
            Kast Productions
          </Box>{" "}
          is design & frontend web development consultancy.
        </Text>
      </Stack>
      <Canvas dpr={[1.5, 2]} linear shadows>
        <fog attach="fog" args={["#272730", 16, 30]} />
        <ambientLight intensity={0.75} />
        {/* @ts-ignore */}
        <PerspectiveCamera makeDefault position={[0, 0, 16]} fov={75}>
          <pointLight intensity={1} position={[-10, -25, -10]} />
          <spotLight
            castShadow
            intensity={2.25}
            angle={0.2}
            penumbra={1}
            position={[-25, 20, -15]}
            shadow-mapSize={[1024, 1024]}
            shadow-bias={-0.0001}
          />
        </PerspectiveCamera>
        <Suspense fallback={null}>
          <Model url="/scene.glb" />
        </Suspense>
        <OrbitControls autoRotate enablePan={false} enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
        <Stars radius={500} depth={50} count={1000} factor={10} />
      </Canvas>
      <div className="layer" />
      <Loader />
    </Box>
  )
}
